### PR TITLE
Constrain `pandas` only on the major version

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
There is no upper-bound constraint upstream: https://github.com/lux-org/lux/pull/428

I pinned to the major version as it's easy to bump that if-and-when `pandas` releases a 2.0.0 version

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
> *I've also updated the requirements to require pandas>= 1.3.0*

Might need to add a minimum constrain... though it doesn't seem to be implemented upstream?
https://github.com/lux-org/lux/pull/428/files#r782649741

**Comment by dhirschfeld** [comment]
:point_up: Looks like we're ok with the minimum version

> *The PR fix does now support the most up to date version of `pandas` and `pandas<1.3`. In `lux/core/__init__`, I check for the version, so the correct variable assignment is completed based on the version.*
>
> *`pandas` 1.2 should work as expected*

**Comment by dorisjlee** [comment]
Thanks @dhirschfeld! This issue is fixed in the latest v0.5 release!

**Pull request closed without merging**
